const actionType = {
    AUTH_START: "AUTH_START",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_FAIL: "AUTH_FAIL",
    AUTH_LOGOUT: "AUTH_LOGOUT",

    JOBGROUPS_START: "JOBGROUPS_START",
    JOBGROUPS_GETALL_SUCCESS: "JOBGROUPS_GETALL_SUCCESS",
    JOBGROUPS_GET_ALL_BY_USERID_SUCCESS: "JOBGROUPS_GET_ALL_BY_USERID_SUCCESS",
    JOBGROUPS_FAIL: "JOBGROUPS_FAIL"

}

export default actionType