const actionType = {
    AUTH_START: "AUTH_START",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_FAIL: "AUTH_FAIL",
    AUTH_LOGOUT: "AUTH_LOGOUT",

    JOBGROUPS_START: "JOBGROUPS_START",
    JOBGROUPS_GETALL_SUCCESS: "JOBGROUPS_GETALL_SUCCESS",
    JOBGROUPS_GET_ALL_BY_USERID_SUCCESS: "JOBGROUPS_GET_ALL_BY_USERID_SUCCESS",
    JOBGROUPS_GET_BY_ID_SUCCESS: "JOBGROUPS_GET_BY_ID_SUCCESS",
    JOBGROUPS_FAIL: "JOBGROUPS_FAIL",

    JOB_POSTING_START: "JOB_POSTING_START",
    JOB_POSTING_GET_BY_JOBGROUP_ID_SUCCESS: "JOB_POSTING_GET_BY_JOBGROUP_ID_SUCCESS",
    JOB_POSTING_FAIL: "JOB_POSTING_FAIL",

}

export default actionType